### ISSUE TITLE
Prikaz skupin

### ISSUE THREAD

**Issue by jharej** [atlet/GroupShift#1]
Na seznamu se ne prikažejo vse skupine.  Vstopil sem v učilnico https://test.skupnost.sio.si/course/view.php?id=9828, naredil dve prazni skupini. Nobena se na seznamu skupin ne prikaže. Nato sem v eno dodal enega udeleženca - prikazala se je na drugem seznamu, na prvem pa ne.

**Comment by atlet** [comment]
Urejeno.
